i_filename = "to_unpack"
i_funcname = "_0x20a5('"
i_big_arr = [
    "show",
    "length",
    "#avatar_name_text",
    "is_typing",
    "post",
    "offsetHeight",
    "support_name",
    "unban",
    "comments",
    "requesting",
    "</div>\n\t\t",
    ".smile_container",
    "getItem",
    "paste",
    "websocket.js: Opened",
    "col_active",
    "1f6",
    "http://localhost:3000",
    "https://cs.money/sounds/support_notification.mp3",
    "#prev_online_chat",
    "обмен",
    "january",
    "switchToComment",
    "prototype",
    "dispatchEvent",
    "/transfer_inventory",
    "switchToRating",
    "forEach",
    "user_mode",
    "mode",
    "_current_month",
    "innerText",
    "File size limit is 5 MB.",
    "2f6",
    ".svg\">",
    "rangeCount",
    "\">\n\t\t\t\t\t\t\t\t\t<div class=\"message_",
    "col",
    "count",
    "clipboardData",
    "Other",
    "</div>\n            </div>",
    "/save_console_errors",
    ".message_user_view",
    "switchToChat",
    "disabled",
    "_render",
    "<img src=\"https://support.cs.money/support/images/2f6",
    "#online_chat_month",
    "online_chat",
    "feedback_about_new_cs_money",
    "removeEventListener",
    "Поделиться своими впечатлениями о new.cs.money",
    "hasAttribute",
    "classList",
    "#chat_rating",
    ".cloud_support_work",
    "Сентября",
    "title",
    "can_give_feedback",
    "font",
    "date",
    "https://support.cs.money/get_virtual_items",
    "june",
    "save",
    "&amp;",
    "#online_chat_send_message",
    "#chat-info-btns",
    "none",
    "#online_chat_calendar_prev",
    "body",
    "december",
    "#smile_header_block",
    ".online_chat_header",
    "search",
    "#online_chat_turn_sound",
    "log",
    "switchToFaq",
    "prevState",
    "Enter",
    "listen",
    "add",
    "getDate",
    "</div>\n                    </div>\n\t\t\t\t\t\t\t      ",
    "Мая",
    "switchToFeedback",
    "Апреля",
    "POPULAR QUESTIONS",
    "modal_big_img",
    "get",
    "tagName",
    "closest",
    "find",
    "Developer",
    "You can only attach jpeg or png images.",
    "Error_2",
    "name",
    "start_work_time",
    ".h2cScript",
    "December",
    "getDomElement",
    "contains",
    "addEventListener",
    "may",
    ".online_chat_hints_title",
    "removeChild",
    "rating_opened",
    "трейд",
    "onerror",
    "messages",
    "https://bit.ly/3aXNjy1",
    "img_ref",
    "Range",
    "every",
    "height: ",
    "_current_year",
    "check",
    "keys",
    "toLocaleUpperCase",
    "div",
    "toString",
    "transferInventory",
    "click",
    "_setCss",
    "_timeout",
    "#online_chat_close",
    "<div class=\"message_user_view\">edited</div>",
    "support_domain",
    "February",
    "/get_support_faq_questions?language=en",
    "innerHTML",
    "#image_viewer",
    "saf",
    "#online_chat_faq",
    "animation_close",
    "Share your feedback about new.cs.money",
    "onreadystatechange",
    "оверсток",
    "setOnMessageCallback",
    "online_chat_feedback_item",
    "<br><iframe width=\"245\" height=\"215\" src=\"https://www.youtube.com/embed/$2\" frameborder=\"0\" allowfullscreen></iframe><br>",
    "#online_chat_calendar_head_mouth",
    "<a href=\"$1\" target=\"_blank\">$1</a>",
    "h2cScript",
    "_setAttr",
    "localhost",
    "display",
    "feedbackPositive",
    "#support_typing",
    "#last_support_message",
    "user",
    "getTime",
    "#chat_ready_button",
    "#online_chat_file_input",
    "getDay",
    ".online_chat_main_container",
    ".online_chat_calendar_container",
    "input",
    "readAsDataURL",
    "touchstart touchmove touchend",
    "init",
    "Почему я не могу забрать свои вещи?",
    "/send_message?language=",
    "\" src=\"",
    "trim",
    "#online_chat",
    "setTimeout",
    "Августа",
    "_text\">",
    "removeAttribute",
    "#online_chat_hints_block",
    "error",
    "April",
    "#sticker_container",
    "getMinutes",
    "_getCss",
    "createDocumentFragment",
    "https://support.cs.money/get_user_group",
    "switchToSupport",
    "Calendar._render",
    "src",
    "prime",
    "animationend",
    ".sound_inactive",
    "getAsFile",
    "setRequestHeader",
    "#online_chat_call",
    ".online_chat_hints_container",
    "new.cs.money",
    "anchorNode",
    "time",
    "getTimezoneOffset",
    "\">\n\t\t\t          <div class=\"message_",
    "status",
    "august",
    "setItem",
    "get_screen",
    "text",
    "October",
    "&#x27;",
    "connect_tries",
    "img",
    "on_message_callback",
    "march",
    "https://support.cs.money/support/images/avatars/",
    "Защититься от скамеров",
    "isArray",
    "other",
    "items",
    "then",
    "/edit_message",
    ".online_chat_drop_container",
    "/rate_supporter",
    "#online_chat_tell",
    "withCredentials",
    "toggle",
    "#online_chat_calendar_table",
    "#online_chat_curr_search_result",
    "scrollTop",
    "#chat_feedback_positive",
    "ban_message",
    "toggleClass",
    "buy",
    "draggable",
    " \n\t\t\t",
    "Why can't I take my items?",
    ".emoji_call",
    "Февраля",
    "addClass",
    "#online_chat_edit_message",
    "timeout",
    "#emoji_container",
    "img_height",
    "getSelection",
    "append",
    "container",
    ".avatar_support_img",
    "anchorOffset",
    "width: ",
    "</div><div class=\"row_table\">",
    "group",
    "#online_chat_faq_search",
    "/get_all_messages",
    "attr",
    "&#x2F;",
    "switchToPositiveFeedback",
    "querySelector",
    "<div class=\"row_table row_table_header\">\n                  <div class=\"col\">MON</div><div class=\"col\">TUE</div><div class=\"col\">WED</div>\n                  <div class=\"col\">THU</div><div class=\"col\">FRI</div><div class=\"col\">SAT</div>\n                  <div class=\"col\">SUN</div>\n\t\t\t\t  </div><div class=\"row_table\">",
    "ceil",
    "indexOf",
    "</div>\n                <svg class=\"\">\n                  <use  xlink:href=\"#svg_icon_arrow_down\"></use>\n                </svg>\n              </div>\n              <div class=\"online_chat_faq_text\">\n                  ",
    "get_logs",
    "img_width",
    ".support_buttons",
    "ban",
    "close_tickets",
    ".emoji_pick",
    "image_type_alert",
    "getAttribute",
    "; domain=",
    "key",
    "bounceInUp",
    "#online_chat_search_input",
    "https://support.cs.money",
    "/set_statistic_open_faq_option",
    ".online_chat_faq_text",
    "\">\n\t\t\t<use  xlink:href=\"#pencil1\"></use>\n\t\t</svg>",
    "feedback",
    "/should_transfer_inventory?game=730",
    "Вы можете прикреплять только jpeg и png изображения.",
    "childNodes",
    "message_user_view",
    "replyMessage",
    ".cloud_support_problems",
    "parentElement",
    "appendChild",
    "july",
    "#online_chat_calendar_table .col[day=\"",
    "stringify",
    "toLowerCase",
    "pathname",
    "nextMonth",
    "#online_chat_editable_message",
    "dataTransfer",
    ".online_chat_faq_main_container",
    "hide",
    "support_assigned",
    "\">\n\t\t\t\t\t\t\t\t\t      <div class=\"message_",
    "supprot",
    "January",
    "\n\t\t\t<div>",
    "hidden",
    "comment",
    "nextElementSibling",
    "script",
    "includes",
    "Вы забанены в чате до ",
    "#online_chat_text_input",
    "dragover dragenter",
    "data",
    "\">\n\t\t\t          <img src=\"",
    "animation_open",
    ".block_title_bots",
    "smile",
    "insertBefore",
    "is_active",
    "jpg",
    "/set_statistic_open_faq",
    "editing",
    "https:&#x2F;&#x2F;www.youtube.com&#x2F;watch?v=",
    "scrollHeight",
    "preventDefault",
    "total",
    "POST",
    "save_console_errors",
    "stopPropagation",
    "#_sup_csrf",
    "<img class=\"sticker\" draggable=\"false\" \n        name=\"2f6",
    "/get_messages?current_count=",
    "August",
    "hasClass",
    "Support",
    "setMonth",
    "#chat_star_wrapper",
    "ontimeout",
    "/set_unread_messages",
    "list",
    "websocket.js: Closed",
    ".online_chat_feedback_item.active",
    "offsetTop",
    "/support/user_ws",
    "highlight",
    "active",
    "scroll",
    "lastChild",
    "offsetWidth",
    "drop",
    "userInventory",
    "overstock",
    "remove",
    "file",
    "Cancel",
    "/online_chat_turn_sound",
    "hold_expiration",
    "notification",
    "#online_chat_calendar_next",
    "edited",
    "IMG",
    "language",
    "click keyup",
    "getBoundingClientRect",
    "https://support.cs.money/support/images/avatars/customer-service.png",
    "<div class=\"message_",
    "_blank",
    "files",
    "/upload_file",
    "\n\t\t\t\t</div>",
    "query",
    "play",
    "</div>\n\t\t\t\t\t\t\t\t\t<div class=\"message_",
    "supportErrors",
    "prevMonth",
    "image",
    "://",
    "removeProperty",
    "&lt;",
    "March",
    "focusOffset",
    "responseText",
    "127.0.0.1",
    "apply",
    "onopen",
    "steamid",
    "\" style=\"",
    "#online_chat_dialog_window",
    "send",
    "split",
    "мод",
    "May",
    "/send_user_screen",
    "_deleteChildren",
    ".info-btn",
    "timeEnd",
    "multipleItems",
    "href",
    "no_bg",
    "$1<a href=\"http://$2\" target=\"_blank\">$2</a>",
    "new_message",
    "change",
    "online_chat_data",
    "pageX",
    ".online_chat_faq_container",
    "method",
    "main",
    "newcsmoney",
    "textContent",
    "cancel",
    "support_steamid",
    "You are banned forever from chat.",
    "querySelectorAll",
    "https://support.cs.money/send_feedback_instruction",
    "Ноября",
    "false",
    "support",
    "getFullYear",
    "clearChatInterface",
    "https://support.cs.money/support/images/avatars/default.png",
    "createElement",
    "focus",
    "July",
    "reverse",
    "Protect from scammers",
    "april",
    "getState",
    "you_are_banned_forever",
    "/open_search_online_chat",
    "className",
    "png",
    "contenteditable",
    "updateState",
    "Октября",
    "ws_protocol",
    "icon_star_container",
    "#hints_close",
    "readyState",
    "children",
    "keyCode",
    "https:&#x2F;&#x2F;youtu.be&#x2F;",
    "#chat_ready_button_positive",
    "create_new_dialog",
    "location",
    "<a href=\"mailto:$1\">$1</a>",
    "support_window_close",
    "removeClass",
    "#online_chat_faq_main_container",
    "Banned",
    "getHours",
    ".message_user_data",
    "Вы навсегда забанены в чате.",
    "\n        <div class=\"online_chat_faq_main_container\">\n            <div class=\"online_chat_faq_container\">\n              <div class=\"online_chat_faq_title superclass_space\">\n                <div >",
    "\">\n\t\t\t\t\t",
    "setAttribute",
    "/get_prime",
    "file_size_limit_alert",
    "push",
    "loadMessageDates",
    "&gt;",
    "#online_chat_drop",
    "Отмена",
    "message_container",
    ".row_table_header",
    "jpeg",
    "role",
    "/support/images/2f6",
    "</div>\n                            <div class=\"message_",
    "nodeType",
    "bot_mode",
    "user_unread",
    "bind",
    "value",
    "playNotification",
    "keyup",
    "substring",
    "url",
    "Максимальный размер файла - 5 Мб.",
    "#online_chat_loading_container",
    "https://support.cs.money/send_hold_message",
    "#online_chat_loading_progress",
    "getMonth",
    "slice",
    "Почему я не могу забрать свой",
    ".online_chat_calendar",
    ".message_user_text",
    "#online_chat_editable_message .message_user_text",
    "true",
    "repeat",
    "&quot;",
    "_getAttr",
    "antiScamBtn",
    "<div class=\"col_active\"></div>",
    "online_chat_editable_message",
    "#image_viewer_img",
    "You are banned from chat untill ",
    "September",
    "GET",
    "#online_chat_all_search_results",
    "type",
    "hostname",
    "range",
    "active_left",
    "parentNode",
    "<img src=\"https://support.cs.money/support/images/1f6",
    "active_next",
    "November",
    "https_support_domain",
    "setTime",
    "ban_end_date",
    "off",
    "tap",
    "/send_amplitude",
    "block",
    "/get_support_faq_questions?language=",
    "#online_chat_support",
    "rating",
    "#chat_feedback",
    "replace",
    "chat",
    "target",
    "css",
    "<img class=\"smile\" draggable=\"false\" \n        name=\"1f6",
    "showDefaultPopup",
    "<div class=\"dialog_container_reply_message_block\">\n                    <div class=\"dialog_container_reply_message\">\n                        <div class=\"reply_line\"></div> \n                        <div class=\"message_",
    "november",
    "onload",
    "setDate",
    "/support/images/attachments/",
    "websocket.js: Connecting... Connection tries: ",
    "experiment_1",
    "loaded",
    "image/png",
    "#ban_message",
    "mute_chat_notifications",
    ".input_text_smile_container",
    "#emoji_call",
    "empty",
    "emoji_pick",
    "faq",
    "shiftKey",
    "toUTCString",
    "_data\">",
    "october",
    "parse",
    "february",
    "open",
    "support_avatar",
    "wss",
    "upload",
    "left",
    "</div>\n\t\t    ",
    ".online_chat_container",
    ".online_chat_button_notification",
    "#support_prime_status",
    "addRange",
    "cookie",
    "connect",
    "unlisten",
    "</div>",
    "trade",
    "experiment_2",
    "you_are_banned_untill",
    "June",
    "firstElementChild",
    "/get_unread_messages",
    ".hints_link",
    "removeAttr",
    "</div>\n\t\t\t\t\t\t\t\t\t      <div class=\"message_",
    "/rate_supporter_only_stars",
    "style",
    "sort",
    "/set_statistic_open_chat",
    "/js/support/html2canvas.js",
    "message_dates",
    "px;",
    "<div class=\"col col_past\">",
    ".smile_header_title",
    "keydown",
    ".stickers_pick",
    ".online_chat_footer",
    "toDataURL",
    ".png\">",
    "</div>\n                        </div>\n                    </div>\n                    <div class=\"message_",
    "currState"
]

with open(i_filename, 'r', encoding='UTF-8') as file:
    with open("unpacked_file", 'w', encoding='UTF-8') as output:
        content = file.read()
        splitted_strings = content.split(i_funcname)
        splitted_strings_2 = []
        output.write(splitted_strings[0])
        for x in range(1, len(splitted_strings)):
            splitted_strings_2 = splitted_strings[x].split("')", 1)
            splitted_strings_2[0] = i_big_arr[int(splitted_strings_2[0], 16)]
            output.write(splitted_strings_2[0] + '`' + splitted_strings_2[1] + '`')
